# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: py/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10py/service.proto\x12\x02pb\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0fMessage2Request\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rMessage2Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0fMessage3Request\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rMessage3Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xab\x01\n\x07Greeter\x12\x32\n\x08SayHello\x12\x12.pb.MessageRequest\x1a\x10.pb.MessageReply\"\x00\x12\x35\n\tSayHello2\x12\x13.pb.Message2Request\x1a\x11.pb.Message2Reply\"\x00\x12\x35\n\tSayHello3\x12\x13.pb.Message3Request\x1a\x11.pb.Message3Reply\"\x00\x42\x06Z\x04./pbb\x06proto3')



_MESSAGEREQUEST = DESCRIPTOR.message_types_by_name['MessageRequest']
_MESSAGEREPLY = DESCRIPTOR.message_types_by_name['MessageReply']
_MESSAGE2REQUEST = DESCRIPTOR.message_types_by_name['Message2Request']
_MESSAGE2REPLY = DESCRIPTOR.message_types_by_name['Message2Reply']
_MESSAGE3REQUEST = DESCRIPTOR.message_types_by_name['Message3Request']
_MESSAGE3REPLY = DESCRIPTOR.message_types_by_name['Message3Reply']
MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageReply = _reflection.GeneratedProtocolMessageType('MessageReply', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREPLY,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.MessageReply)
  })
_sym_db.RegisterMessage(MessageReply)

Message2Request = _reflection.GeneratedProtocolMessageType('Message2Request', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE2REQUEST,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.Message2Request)
  })
_sym_db.RegisterMessage(Message2Request)

Message2Reply = _reflection.GeneratedProtocolMessageType('Message2Reply', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE2REPLY,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.Message2Reply)
  })
_sym_db.RegisterMessage(Message2Reply)

Message3Request = _reflection.GeneratedProtocolMessageType('Message3Request', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE3REQUEST,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.Message3Request)
  })
_sym_db.RegisterMessage(Message3Request)

Message3Reply = _reflection.GeneratedProtocolMessageType('Message3Reply', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE3REPLY,
  '__module__' : 'py.service_pb2'
  # @@protoc_insertion_point(class_scope:pb.Message3Reply)
  })
_sym_db.RegisterMessage(Message3Reply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _MESSAGEREQUEST._serialized_start=24
  _MESSAGEREQUEST._serialized_end=54
  _MESSAGEREPLY._serialized_start=56
  _MESSAGEREPLY._serialized_end=87
  _MESSAGE2REQUEST._serialized_start=89
  _MESSAGE2REQUEST._serialized_end=120
  _MESSAGE2REPLY._serialized_start=122
  _MESSAGE2REPLY._serialized_end=154
  _MESSAGE3REQUEST._serialized_start=156
  _MESSAGE3REQUEST._serialized_end=187
  _MESSAGE3REPLY._serialized_start=189
  _MESSAGE3REPLY._serialized_end=221
  _GREETER._serialized_start=224
  _GREETER._serialized_end=395
# @@protoc_insertion_point(module_scope)
